CAVEI1.FILE: cavei1.lf
FILLINFO2.PGM: fillinfo2.pgm.sqlrpgle INFOCENTRE.FILE VINI1.FILE CAVEI1.FILE
FILLINFO3.PGM: fillinfo3.pgm.sqlrpgle
FILLINFOC.PGM: fillinfoc.pgm.rpgle INFOCENTRE.FILE VINI1.FILE CAVEI1.FILE
INFOCENTL1.FILE: infocentl1.lf INFOCENTRE.FILE
MENUC.PGM: menuc.pgm.clle MENUD.FILE
MENUD.FILE: menud.dspf
MNTINFOC.PGM: mntinfoc.pgm.rpgle MNTINFOCD.FILE INFOCENTRE.FILE INFOCENTL1.FILE
MNTINFOCD.FILE: mntinfocd.dspf INFOCENTRE.FILE
MNTINFOCS.PGM: mntinfocs.pgm.sqlrpgle MNTINFOCSD.FILE INFOCENTRE.FILE
MNTINFOCSD.FILE: mntinfocsd.dspf INFOCENTRE.FILE
MODMSGS.MODULE: modmsgs.rpgle
PRTINFOC.PGM: prtinfoc.pgm.rpgle
PRTINFOCP.FILE: prtinfocp.prtf INFOCENTRE.FILE
VINI1.FILE: vini1.lf